FROM python:3.7

WORKDIR /usr/src/app

RUN pip3 install psycopg2

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

ENV FLASK_APP=./app.py
ENV FLASK_DEBUG=True

CMD ["python", "app.py"]